### ISSUE TITLE
Wondering how to convert this to Keras?

### ISSUE THREAD

**Issue by sharpe5** [jxbz/agd#1]
I use Keras, and I'd love to run it through its paces in my ML pipeline. 

Wondering what would be involved to convert this to work with Keras? Or if anyone has a Keras implementation they are working on? Happy to contribute if I could be pointed in the right direction.

**Comment by jxbz** [comment]
Hey @sharpe5, thanks for your interest in this!

I just had a quick look at how Keras handles optimizers. It seems the main difference to what we're doing is that you'd need to separately handle weight initialisation and writing a custom optimiser. In contrast, in our pytorch implementation we have a single class in `agd.py` that does both.

- for weight initialisation, you could use `tf.keras.initializers.Orthogonal` (described [here](https://keras.io/api/layers/initializers/#orthogonal-class)) and set the gain as described in our paper
- for writing a custom optimiser, I think you'd need to follow the pattern used for `keras/optimizers/sgd.py` (see [here](https://github.com/keras-team/keras/blob/v2.12.0/keras/optimizers/sgd.py))

Let me know if you do give it a go. I'm happy to help debug if you run into any problems

**Comment by sharpe5** [comment]
Excellent, thanks! I'll give it a shot. I was so impressed by the paper that I
think more people should have access to it.
